apiVersion: aws.hops.ops.com.ai/v1alpha1
kind: CrossplaneStack
metadata:
  name: crossplane
  namespace: default
spec:
  clusterName: production
  labels:
    team: platform
    environment: production
  install:
    namespace: crossplane-system
    name: crossplane
    values:
      resourcesCrossplane:
        requests:
          cpu: 500m
          memory: 1Gi
