apiVersion: stacks.aws.hops.ops.com.ai/v1alpha1
kind: CrossplaneStack
metadata:
  name: crossplane
  namespace: default
spec:
  clusterName: production
  labels:
    team: platform
    environment: production
  tags:
    team: platform
    environment: production
  aws:
    region: us-east-1
    tags:
      cost-center: platform
  providers:
    aws:
      enabled: true
      providers:
        iam: {}
        s3: {}
        ec2: {}
    kubernetes:
      enabled: true
    helm:
      enabled: true
    github:
      enabled: true
      githubOrg: my-org
      secretName: github-provider-token
  functions:
    autoReady: true
