apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kubernetesproviderstacks.crossplane.hops.ops.com.ai
spec:
  compositeTypeRef:
    apiVersion: crossplane.hops.ops.com.ai/v1alpha1
    kind: KubernetesProviderStack
  mode: Pipeline
  pipeline:
  - functionRef:
      name: hops-ops-aws-crossplane-stackkubernetes-provider
    step: kubernetes-provider
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
