apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: awsproviderstacks.crossplane.hops.ops.com.ai
spec:
  compositeTypeRef:
    apiVersion: crossplane.hops.ops.com.ai/v1alpha1
    kind: AWSProviderStack
  mode: Pipeline
  pipeline:
  - functionRef:
      name: hops-ops-aws-crossplane-stackaws-provider
    step: aws-provider
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
