apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: zitadelproviderstacks.crossplane.hops.ops.com.ai
spec:
  compositeTypeRef:
    apiVersion: crossplane.hops.ops.com.ai/v1alpha1
    kind: ZitadelProviderStack
  mode: Pipeline
  pipeline:
  - functionRef:
      name: hops-ops-aws-crossplane-stackzitadel-provider
    step: zitadel-provider
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
