apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: functionsstacks.crossplane.hops.ops.com.ai
spec:
  compositeTypeRef:
    apiVersion: crossplane.hops.ops.com.ai/v1alpha1
    kind: FunctionsStack
  mode: Pipeline
  pipeline:
  - functionRef:
      name: hops-ops-aws-crossplane-stackfunctions
    step: functions
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
