name: on-push-main

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/on-push-main.yaml"
      - ".github/workflows/on-version-tagged.yaml"
      - ".gitops/**"
      - "apis/**"
      - "examples/**"
      - "functions/**"
      - "tests/**"
      - "upbound.yaml"

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write # Required for OIDC auth

jobs:
  validate:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/validate.yaml@v3.0.0
    with:
      examples: |
        [
          { "example": "examples/crossplanestacks/minimal.yaml", "api_path": "apis/crossplanestacks" },
          { "example": "examples/crossplanestacks/standard.yaml", "api_path": "apis/crossplanestacks" },
          { "example": "examples/crossplanestacks/full.yaml", "api_path": "apis/crossplanestacks" },
          { "example": "examples/awsproviderstacks/minimal.yaml", "api_path": "apis/awsproviderstacks" },
          { "example": "examples/awsproviderstacks/full.yaml", "api_path": "apis/awsproviderstacks" },
          { "example": "examples/functionsstacks/minimal.yaml", "api_path": "apis/functionsstacks" },
          { "example": "examples/functionsstacks/full.yaml", "api_path": "apis/functionsstacks" },
          { "example": "examples/githubproviderstacks/minimal.yaml", "api_path": "apis/githubproviderstacks" },
          { "example": "examples/githubproviderstacks/full.yaml", "api_path": "apis/githubproviderstacks" },
          { "example": "examples/helmproviderstacks/minimal.yaml", "api_path": "apis/helmproviderstacks" },
          { "example": "examples/helmproviderstacks/full.yaml", "api_path": "apis/helmproviderstacks" },
          { "example": "examples/kubernetesproviderstacks/minimal.yaml", "api_path": "apis/kubernetesproviderstacks" },
          { "example": "examples/kubernetesproviderstacks/full.yaml", "api_path": "apis/kubernetesproviderstacks" },
          { "example": "examples/listmonkproviderstacks/minimal.yaml", "api_path": "apis/listmonkproviderstacks" },
          { "example": "examples/listmonkproviderstacks/full.yaml", "api_path": "apis/listmonkproviderstacks" },
          { "example": "examples/openpanelproviderstacks/minimal.yaml", "api_path": "apis/openpanelproviderstacks" },
          { "example": "examples/openpanelproviderstacks/full.yaml", "api_path": "apis/openpanelproviderstacks" },
          { "example": "examples/zitadelproviderstacks/minimal.yaml", "api_path": "apis/zitadelproviderstacks" },
          { "example": "examples/zitadelproviderstacks/full.yaml", "api_path": "apis/zitadelproviderstacks" }
        ]
      error_on_missing_schemas: true

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v3.0.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v3.0.0
    with:
      aws: true
      aws-use-oidc: true
      aws-account-id: "034489662075"
      aws-region: us-east-2
      aws-role-duration-seconds: 7200
      write-env-files: true
      env-vars: |
        {
          "ADMIN_ROLE_ARN": "${{ vars.ADMIN_ROLE_ARN }}",
          "PRIVATE_SUBNET_ID_A": "${{ vars.PRIVATE_SUBNET_ID_A }}",
          "PRIVATE_SUBNET_ID_B": "${{ vars.PRIVATE_SUBNET_ID_B }}"
        }
      debug-resource-types: |
        [
          "crossplanestacks.aws.hops.ops.com.ai"
        ]
      delete-extra-resources: |
        [
          "autoeksclusters.aws.hops.ops.com.ai"
        ]
      timeout-minutes: 44
      cleanup-timeout-minutes: 20
      delete-extra-resources-timeout-minutes: 20

  version-and-tag:
    name: Version and Tag
    needs:
      - validate
      - test
      - e2e
    uses: unbounded-tech/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.21.3
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    with:
      useDeployKey: true
