name: on-push-main

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/on-push-main.yaml"
      - ".github/workflows/on-version-tagged.yaml"
      - ".gitops/**"
      - "Makefile"
      - "apis/**"
      - "examples/**"
      - "functions/**"
      - "scripts/**"
      - "tests/**"
      - "upbound.yaml"

permissions:
  packages: write
  contents: write
  issues: write
  pull-requests: write
  id-token: write # Required for OIDC auth

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache crossplane
        uses: actions/cache@v5
        with:
          path: |
            ~/.crossplane/cache
            ~/.up/cache
            ~/.up/build-cache
          key: ${{ runner.os }}-crossplane-${{ hashFiles('**/upbound.yaml','**/definition.yaml') }}-

      - name: Install up
        env:
          UP_VERSION: v0.46.0
        run: |
          set -euo pipefail
          curl --fail --location --retry 5 --retry-all-errors --retry-delay 5 \
            "https://cli.upbound.io/stable/${UP_VERSION}/bin/linux_amd64/up" \
            --output up
          chmod +x up
          sudo mv up /usr/local/bin/up
          up version

      - name: Install Crossplane CLI
        run: |
          curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh \
            | XP_VERSION=v2.0.2 sh

      - name: Docker login to GHCR
        uses: docker/login-action@v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build with up
        uses: upbound/action-up-project@v1.1.2
        with:
          skip-login-check: true

      - name: Validate all examples
        run: scripts/ci-validate-all.sh

  test:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/test.yaml@v3.0.0

  e2e:
    uses: unbounded-tech/workflows-crossplane/.github/workflows/e2e.yaml@v3.0.0
    with:
      aws: true
      aws-use-oidc: true
      aws-account-id: "034489662075"
      aws-region: us-east-2
      aws-role-duration-seconds: 7200
      write-env-files: true
      env-vars: |
        {
          "ADMIN_ROLE_ARN": "${{ vars.ADMIN_ROLE_ARN }}",
          "PRIVATE_SUBNET_ID_A": "${{ vars.PRIVATE_SUBNET_ID_A }}",
          "PRIVATE_SUBNET_ID_B": "${{ vars.PRIVATE_SUBNET_ID_B }}"
        }
      debug-resource-types: |
        [
          "crossplanestacks.aws.hops.ops.com.ai"
        ]
      delete-extra-resources: |
        [
          "autoeksclusters.aws.hops.ops.com.ai"
        ]
      timeout-minutes: 44
      cleanup-timeout-minutes: 20
      delete-extra-resources-timeout-minutes: 20

  version-and-tag:
    name: Version and Tag
    needs:
      - validate
      - test
      - e2e
    uses: unbounded-tech/workflow-vnext-tag/.github/workflows/workflow.yaml@v1.21.3
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    with:
      useDeployKey: true
